### ISSUE TITLE
All provinces convert as ‘state’ in EU4

### ISSUE THREAD

**Issue by Nyarukocqc** [ParadoxGameConverters/CK3toEU4#206]
![image](https://user-images.githubusercontent.com/51341357/121272956-c3a95b00-c8f9-11eb-83e4-9037f5d3ac7e.png)

This will result in severe penalties if player rules a big empire above 750 developments,After 400 years(or even 600 years) expansion in CK3,This usually happen.

**Comment by Zemurin** [comment]
This isn't actually the case:
1. Usually the game decides what should be state and what not according to its own algorithm on game start. It's common to see large empires convert and when loaded only the capital state is state, rest is all territories since otherwise they would be hugely over govcap.
2. There isn't a method for a mod to mark a state as a state - we cannot say "this is territory, that is state".

As such, if you convert with a rome-sized country, you can do these things:
1. Suck it up and deal with the insane penalties to simulate internal instability and issues
2. Shatter it HRE-style and play a prince
3. Unstate everything and roleplay a paper tiger.

Either case, nothing we can do.
