### ISSUE TITLE
Error on conversion when not shattering Roman Empire

### ISSUE THREAD

**Issue by cornytrace** [ParadoxGameConverters/CK3toEU4#244]
In CK3 I reformed the Roman Empire, destroying the HRE and Byzantium. When specifying I don't want the HRE or shattering in the converter it errors at 55%. When I specify Rome it works, although with some warnings and even errors. But that leave the emperor with only frisia and carpathia, other parts of the empire aren't  vassals or even personal unions, they are independent.
[log.txt](https://github.com/ParadoxGameConverters/CK3toEU4/files/6988154/log.txt)
Save game link: https://we.tl/t-BmsQaUHNU0

**Comment by Zemurin** [comment]
```2021-08-15 15:03:05    [ERROR] Clay for d_lower_bosna has no title definition! THIS IS BAD! Are you converting an old save against a new CK3 version?```

Is this a save imported from an old version of CK3?

**Comment by cornytrace** [comment]
I know for certain the version was at least 1.4, due to the play dates. I've tried all ck3 beta branches of 1.4, all give the same error.

**Comment by Zemurin** [comment]
I'm seeing c_kintus error meaning this particular save has been started in 1.2 and loaded in 1.4, which corrupted it. As a result titles such as c_jovvkuj have been destroyed by their holders and save where *counties* are destroyed are a red flag for any internal consistency.

Feel free to load the save, go to jovvkuj and see that it doesn't exist - that's dead land right there. Ckeck kintus while at it and other changed provinces since 1.2.
